name: Install Dependencies
description: Install the correct dependencies to build Endless Sky Mission Builder
runs:
    using: 'composite'
    steps:
        - if: runner.os == 'Linux'
          run: |
              sudo apt update
              sudo apt install -y --no-install-recommends ccache
          
          - name: Install Qt
            uses: jurplel/install-qt-action@v3
            id: install-qt
            with:
                version: '6.3.1'
                host: 'linux'
                cache: 'true'
          
          - name: Download and install Boost
            uses: MarkusJx/install-boost@v2.4.0
            id: install-boost
            with:
                boost_version: 1.73.0

        env:
            BOOST_ROOT: ${{ steps.install-boost.outputs.BOOST_ROOT }}
