name: CD

concurrency: 
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

on:
    push: 
        branches: [ "cpp-conversion" ]
    pull_request:
    workflow_dispatch:

env:
    # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
    BUILD_TYPE: Debug

jobs:
    ubuntu_x86_64:
        name: Ubuntu 20.04 x64 Continuous
        runs-on: ubuntu-20.04
        container: ghcr.io/shitwolfymakes/esmb-ci:v1.2.3
        env:
            ARCH: x86_64
            OUTPUT: ESMB-Ubuntu-20.04-x86_64-continuous.tar.gz
        
        steps:
            - uses: actions/checkout@v3
            
            - name: Configure CMake
              run: cmake -S . -B build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

            - name: Build
              # Build your program with the given configuration
              run: cmake --build build --config ${{env.BUILD_TYPE}}
            
            # ensure files are where expected
            - run: ls -l ./build/src/esmb ./build/tests
            - name: Package Application
              # TODO: write a packager script
              run: tar -czf ${{ env.OUTPUT }} ./build/src/esmb/esmb ./build/tests/filefilteritemparser_tests ./build/tests/fileitemparser_tests ./build/tests/filemissionitemparser_tests ./build/tests/filephraseitemparser_tests ./build/tests/filesubstitutionsitemparser_tests
            
            - name: Upload build artifacts
              uses: actions/upload-artifact@v3.1.1
              with:
                  name: ${{ env.OUTPUT }}
                  path: ${{ env.OUTPUT }}

    release_continuous_build:
        if: github.event_name != 'pull_request'
        runs-on: ubuntu-latest
        needs:
            - ubuntu_x86_64
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            OUTPUT_UBUNTU: ESMB-Ubuntu-20.04-x86_64-continuous.tar.gz
        
        steps:
            - uses: actions/checkout@v3
            
            - name: Install github-release
              run: |
                  go install github.com/github-release/github-release@latest
                  echo "GOPATH=$(go env GOPATH)" >> $GITHUB_ENV
                  echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
            
            - name: Set environment variables
              run: |
                  echo "GITHUB_USER=$( echo ${{ github.repository }} | cut -d/ -f1 )" >> $GITHUB_ENV
                  echo "GITHUB_REPO=$( echo ${{ github.repository }} | cut -d/ -f2 )" >> $GITHUB_ENV
            
            - name: Move/Create continuous tag
              run: |
                  git tag --force continuous ${{ github.sha }}
                  git push --tags --force
            
            - name: Setup continuous release
              run: |
                  DESCRIPTION="Triggered on $(date -u '+%Y/%m/%d, %H:%M') UTC by commit ${{ github.sha }} (@${{ github.actor }})
                  This is an automated build of the latest source. It includes ESMB and all the unit test binaries. It may be unstable or even crash, corrupt your save or eat your kitten. Use with caution!
                  https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
                  if ! github-release info -t continuous > /dev/null 2>&1; then
                      github-release release \
                          --tag continuous \
                          --name "Continuous Build" \
                          --description "$DESCRIPTION" \
                          --pre-release
                  else
                      github-release edit \
                          --tag continuous \
                          --name "Continuous Build" \
                          --description "$DESCRIPTION" \
                          --pre-release
                  fi
            
            - name: Download Artifacts
              uses: actions/download-artifact@v3
              with:
                  path: ${{ github.workspace }}
            
            - name: Add ${{ env.OUTPUT_UBUNTU }} to release tag
              run: |
                  github-release upload \
                      --tag continuous \
                      --replace \
                      --name ${{ env.OUTPUT_UBUNTU }} \
                      --file ${{ env.OUTPUT_UBUNTU }}/${{ env.OUTPUT_UBUNTU }}
