name: CI Tests

concurrency: 
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

on:
    push:
        branches: [ "cpp-conversion", "cicd-buildout" ]
    pull_request:
        types:
            - synchronize
            - open
    workflow_dispatch:

env:
    # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
    BUILD_TYPE: Debug

jobs:
    build:
        runs-on: ubuntu-latest
        container: ghcr.io/shitwolfymakes/esmb-ci:v1.2.0
        steps:
        - uses: actions/checkout@v3

        - name: Configure CMake
          run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

        - name: Build
          # Build your program with the given configuration
          run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

        - name: Test
          working-directory: ${{github.workspace}}/build/tests
          run: for f in ./*_tests; do ./$f; done
      
