name: CI Tests

concurrency: 
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

on:
    push:
        branches: [ "cpp-conversion", "cicd-buildout" ]
    pull_request:
    workflow_dispatch:

env:
    # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
    BUILD_TYPE: Debug

jobs:
    ci_build_tests:
        runs-on: ubuntu-latest
        container: ghcr.io/shitwolfymakes/esmb-ci:v1.2.3
        steps:
            - uses: actions/checkout@v3

            - name: Configure CMake
              run: cmake -S . -B build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

            - name: Build
              # Build your program with the given configuration
              run: cmake --build build --config ${{env.BUILD_TYPE}}

            - name: Test
              working-directory: ./build/tests
              run: for f in ./*_tests; do ./$f; done
      
    ci_test_coverage:
        runs-on: ubuntu-latest
        container: ghcr.io/shitwolfymakes/esmb-ci:v1.2.3
        steps:
            - uses: actions/checkout@v3
            - name: Run CMake
              run: cmake -S . -B build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
            - name: Build
              run: cmake --build build --config ${{env.BUILD_TYPE}}
            - name: Archive coverage report
              uses: actions/upload-artifact@v3
              with:
                  name: code-coverage-report
                  path: ./build/html
            - name: Publish report to Coveralls
              uses: coverallsapp/github-action@master
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  path-to-lcov: ./build/json.info.filtered.noexcept
