name: CI Tests

concurrency: 
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

on:
    push:
    pull_request:
    workflow_dispatch:

env:
    # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
    BUILD_TYPE: Debug

jobs:
    ci_test_coverage:
        runs-on: ubuntu-latest
        container: ghcr.io/shitwolfymakes/esmb-ci:v1.2.3
        steps:
            - uses: actions/checkout@v3
            
            - name: Run CMake
              run: CXX="g++ --coverage -fprofile-arcs -ftest-coverage" cmake -S . -B build_coverage -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
              
            - name: Build
              run: cmake --build build_coverage --config ${{env.BUILD_TYPE}}

            - name: Run Tests
              working-directory: ./build_coverage/tests
              run: for f in ./*_tests; do ./$f; done
            - run: ls -al . ./build_coverage ./build_coverage/tests
              
            - run: lcov --directory . --remove ./build_coverage --capture --output-file coverage.info --rc lcov_branch_coverage=1
            - run: genhtml --title "Endless Sky Mission Builder" coverage.info --output-directory lcov_out
            - run: ls -al . ./build_coverage ./lcov_out
            
            - name: Archive coverage report
              uses: actions/upload-artifact@v3
              with:
                  name: code-coverage-report
                  path: ./lcov_out
            
            - name: Publish report to Coveralls
              uses: coverallsapp/github-action@1.1.3
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  path-to-lcov: ./coverage.info
